name: Generate API Schema

on:
  push:
    branches: [ main ]
    paths:
      - '**.py' # Python関連が変わった時だけ実行

jobs:
  generate-type:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install drf-spectacular djangorestframework-camel-case

      - name: Generate Schema
        run: |
          python manage.py spectacular --clean --file schema.yml
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          SECRET_KEY: "ci-test-key"
          APP_ENV: "local"
          AWS_ACCESS_KEY_ID: "dummy"
          AWS_SECRET_ACCESS_KEY: "dummy"
          AWS_STORAGE_BUCKET_NAME: "dummy"
          CLOUDFRONT_DOMAIN: "dummy"
          CLOUDFRONT_PUBLIC_KEY_ID: "dummy"
          # 第一引数に環境変数名、defaultにNoneを指定
          CLOUDFRONT_PRIVATE_KEY: "dummy"
          # キーが存在する場合のみ改行コードの置換処理を行う
          CLOUDFRONT_URL_EXPIRES_SECONDS: "3600"


      - name: Generate TS Types
        run: |
          # 出力先をプロジェクト内の適切な場所に
          npx openapi-typescript schema.yml --output ./types/api-types.ts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate schema and types [skip ci]"
          file_pattern: 'schema.yml ./types/api-types.ts'